---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Zzy_Windows.
--- DateTime: 2025/6/8 下午9:28
---
--- 比较线程标识和锁中的标识是否一致
if (redis.call('get',KEYS[1]) == ARGV[1]) then
  ---释放锁del key
    return redis.call('del', KEYS[1])
end
return 0